[package]
name = "elude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "*"
parking_lot = "*"
libc = "*"

[dev-dependencies]
checkito = "1.3.8"
