[package]
name = "elude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = { version = "*", features = ["deadlock_detection"] }
rayon = "*"
libc = "*"

[dev-dependencies]
checkito = "1.3.8"
criterion = "*"

[[bench]]
name = "multex"
harness = false

[profile.release]
debug = true
opt-level = 0
